### ISSUE TITLE
transition de Sexe vers genre sur la cni et le passeport

### ISSUE THREAD

**Issue by yapudjus** [Listenbourg/GenerateurCNI#5]
## pourquoi ?
 - nous sommes le pays de l’acceptante et de la modernité
 - inclusion des personnes dont le genre ne correspond pas à leur sexe de naissance
-----
je l'aurais biens fait en ouvrant ensuite une pull request, mais ne connaissant pas la police utilisée sur la CNI, je ne souhaitait pas me risquer à dégrader l'identification de nôtre beaux pays

**Comment by thaliumFr** [comment]
Bien le bonjour,
De ce que j'ai vu dans le base.js sur la CNI ce serait la police [HK Grotesk](https://www.dafontfree.io/hk-grotesk-font-family/) qui serait utilisée, une page de branding comme sur [discord](https://discord.com/branding) serait la bienvenue probablement pour permettre d'exposer nos magnifiques couleurs constituant le drapeau, qu'en dite vous?

**Comment by NonozgYtb** [comment]
Concernant le genre, c'est un débat dont le gouvernement reste neutre. Il y a aussi le choix "Non précisé" qui peut correspondre aux personnes non binaires ou du moins qui ne se reconnaisse pas dans ces deux genres ! (Les droits LGBT me tiennent à cœur mais faut suivre la ligne de conduite du gouvernement !)

**Comment by NonozgYtb** [comment]
Le branding (appellé dans le gargon *Design system* n'est pas fini. De plus, c'est je crois prévu mais nous utilisons déjà en interne Figma pour pas mal de chose 😉 !

**Comment by ecnivtwelve** [comment]
Il me semblait important de garder le sexe "X" sur la carte d'identité et je savais que la notion de "sexe/genre" allait poser ses limites. Cependant le genre n'a qu'une valeur sociale et nullement juridique ou officielle, c'est pourquoi j'utilise la notion de sexe, et que l'option non précisé est disponible pour les personnes qui ne sont pas à l'aise avec leur sexe de naissance.
