### ISSUE TITLE
Chartes couleurs

### ISSUE THREAD

**Issue by thaliumFr** [Listenbourg/GenerateurCNI#6]
Notre cher pays du Listenbourg affiche les couleurs du rouge et blanc, le blanc étant utilisé comme couleur principale de fond, au lieu d'utiliser du bleu pour les elements cliquables (boutons, liens, ...) ne serait-il point plus convenable d'y présenter notre bon vieux rouge afin d'omogénéhiser le site?
De plus l'utilisation de variable CSS pourrait faciliter la tache, si vous le souhaiter je peux même m'en charger!

Viva Listenbourg!

**Comment by NonozgYtb** [comment]
La question a été évoqué mais vu que nous utilisons déjà massivement le rouge et ce sera encore plus le cas pour le site principal, nous avons choisi de nous démarqué avec le nom ListenPass, en bleu comme le logo pour permettre de changer un peu ! (Et le bleu est la couleur par défaut des liens !
