### ISSUE TITLE
Please add additional languages 

### ISSUE THREAD

**Issue by Mattis142** [Listenbourg/GenerateurCNI#8]
I want to apply for a Visa but unfortunately do not speak french and therefore it's really hard, my embassy directed me to the website but didn't offer any translation

Please add an option to select more than one language

**Comment by NonozgYtb** [comment]
We are a french community, so now, this feature is not scheduled !

**Comment by thaliumFr** [comment]
what he wanted to say is that as a french based community we first want to do it properly in french, you can use the in-browser page translator for now. We will, in the future, perhaps, think of adding other languages in the process, English being one of the most important as this joke of the Listenbourg was pointing at Americans.
